Type: AWS::RDS::DBInstance
Properties:
  DBInstanceIdentifier: ${self:custom.DB_NAME}
  MasterUsername: ${self:custom.DB_USER}
  MasterUserPassword: ${self:custom.DB_PASSWORD}
  AllocatedStorage: 20
  DBName: ${self:custom.DB_NAME}
  DBInstanceClass: db.t2.micro
  Engine: mysql
  EngineVersion: "8.0"
  PubliclyAccessible: true
  VPCSecurityGroups:
    - !GetAtt MyAccessPolicy.GroupId